"""
Seed the database with realistic sample patients.
Runs once on startup (idempotent — skips if data already present).
"""
from __future__ import annotations
import uuid
from datetime import date
from sqlalchemy import select, func
from sqlalchemy.ext.asyncio import AsyncSession
from app.models.patient import Patient


SAMPLE_PATIENTS: list[dict] = [
    {
        "first_name": "Eleanor", "last_name": "Whitfield",
        "date_of_birth": date(1952, 3, 14), "gender": "female",
        "blood_type": "A+", "email": "eleanor.whitfield@email.com",
        "phone": "555-201-4433", "address": "142 Maple Drive",
        "city": "Portland", "state": "OR", "zip_code": "97201",
        "status": "active", "primary_physician": "Dr. Sarah Chen",
        "insurance_provider": "BlueCross BlueShield", "insurance_id": "BCB-441029",
        "allergies": ["Penicillin", "Sulfa drugs"],
        "medical_notes": "Hypertension managed with lisinopril. Diabetes Type 2 — follow up quarterly.",
        "last_visit_date": date(2026, 4, 10),
    },
    {
        "first_name": "Marcus", "last_name": "Rivera",
        "date_of_birth": date(1985, 7, 22), "gender": "male",
        "blood_type": "O+", "email": "marcus.rivera@email.com",
        "phone": "555-304-8821", "address": "87 Oak Lane",
        "city": "Austin", "state": "TX", "zip_code": "73301",
        "status": "active", "primary_physician": "Dr. James Okafor",
        "insurance_provider": "Aetna", "insurance_id": "AET-992810",
        "allergies": [],
        "medical_notes": "Annual physical completed. Cholesterol slightly elevated — dietary changes recommended.",
        "last_visit_date": date(2026, 3, 5),
    },
    {
        "first_name": "Priya", "last_name": "Nair",
        "date_of_birth": date(1993, 11, 5), "gender": "female",
        "blood_type": "B+", "email": "priya.nair@email.com",
        "phone": "555-410-3374", "address": "23 Birchwood Court",
        "city": "Seattle", "state": "WA", "zip_code": "98101",
        "status": "active", "primary_physician": "Dr. Sarah Chen",
        "insurance_provider": "UnitedHealth", "insurance_id": "UHC-773492",
        "allergies": ["Latex"],
        "medical_notes": "Asthma — uses albuterol inhaler as needed. No recent flare-ups.",
        "last_visit_date": date(2026, 5, 1),
    },
    {
        "first_name": "Harold", "last_name": "Jennings",
        "date_of_birth": date(1945, 1, 30), "gender": "male",
        "blood_type": "AB-", "email": None,
        "phone": "555-518-6690", "address": "9 Elm Street",
        "city": "Denver", "state": "CO", "zip_code": "80201",
        "status": "critical", "primary_physician": "Dr. Linda Park",
        "insurance_provider": "Medicare", "insurance_id": "MCR-001-44-5567",
        "allergies": ["Aspirin", "Codeine"],
        "medical_notes": "Post-op recovery from bypass surgery. Closely monitored in cardiac unit. Do not administer NSAIDs.",
        "last_visit_date": date(2026, 5, 19),
    },
    {
        "first_name": "Amara", "last_name": "Osei",
        "date_of_birth": date(1978, 9, 17), "gender": "female",
        "blood_type": "O-", "email": "amara.osei@email.com",
        "phone": "555-622-1188", "address": "55 Spruce Ave",
        "city": "Atlanta", "state": "GA", "zip_code": "30301",
        "status": "active", "primary_physician": "Dr. James Okafor",
        "insurance_provider": "Cigna", "insurance_id": "CGN-388210",
        "allergies": [],
        "medical_notes": "Migraines managed with sumatriptan. Reports improvement with recent prescription adjustment.",
        "last_visit_date": date(2026, 4, 22),
    },
    {
        "first_name": "Theodore", "last_name": "Blackwood",
        "date_of_birth": date(1961, 6, 8), "gender": "male",
        "blood_type": "A-", "email": "ted.blackwood@email.com",
        "phone": "555-733-9922", "address": "301 Chestnut Blvd",
        "city": "Chicago", "state": "IL", "zip_code": "60601",
        "status": "inactive", "primary_physician": "Dr. Linda Park",
        "insurance_provider": "Humana", "insurance_id": "HUM-004820",
        "allergies": ["Shellfish"],
        "medical_notes": "Inactive — no visits in over 18 months. Last treatment for lower back pain.",
        "last_visit_date": date(2024, 11, 3),
    },
    {
        "first_name": "Sophia", "last_name": "Delacroix",
        "date_of_birth": date(2001, 4, 25), "gender": "female",
        "blood_type": "B-", "email": "sophia.delacroix@email.com",
        "phone": "555-844-2255", "address": "16 Willow Way",
        "city": "New Orleans", "state": "LA", "zip_code": "70112",
        "status": "active", "primary_physician": "Dr. Sarah Chen",
        "insurance_provider": "BlueCross BlueShield", "insurance_id": "BCB-553811",
        "allergies": ["Amoxicillin"],
        "medical_notes": "Anxiety disorder — counseling ongoing. Prescribed sertraline 50mg.",
        "last_visit_date": date(2026, 2, 14),
    },
    {
        "first_name": "Kenji", "last_name": "Watanabe",
        "date_of_birth": date(1970, 12, 3), "gender": "male",
        "blood_type": "AB+", "email": "kenji.watanabe@email.com",
        "phone": "555-911-4400", "address": "404 Redwood Rd",
        "city": "San Francisco", "state": "CA", "zip_code": "94102",
        "status": "active", "primary_physician": "Dr. Rachel Goldstein",
        "insurance_provider": "Kaiser Permanente", "insurance_id": "KP-829374",
        "allergies": [],
        "medical_notes": "Hypothyroidism — levothyroxine 75mcg daily. TSH levels stable.",
        "last_visit_date": date(2026, 1, 28),
    },
    {
        "first_name": "Fatima", "last_name": "Al-Hassan",
        "date_of_birth": date(1988, 2, 14), "gender": "female",
        "blood_type": "O+", "email": "fatima.alhassan@email.com",
        "phone": "555-102-7733", "address": "72 Palm Court",
        "city": "Houston", "state": "TX", "zip_code": "77001",
        "status": "discharged", "primary_physician": "Dr. James Okafor",
        "insurance_provider": "Aetna", "insurance_id": "AET-441987",
        "allergies": ["Ibuprofen"],
        "medical_notes": "Discharged following appendectomy. Recovery uneventful. Follow-up in 6 weeks.",
        "last_visit_date": date(2026, 5, 7),
    },
    {
        "first_name": "Cornelius", "last_name": "Hartmann",
        "date_of_birth": date(1936, 8, 19), "gender": "male",
        "blood_type": "A+", "email": None,
        "phone": "555-234-5566", "address": "88 Magnolia Lane",
        "city": "Nashville", "state": "TN", "zip_code": "37201",
        "status": "critical", "primary_physician": "Dr. Linda Park",
        "insurance_provider": "Medicare", "insurance_id": "MCR-002-88-1104",
        "allergies": ["Warfarin", "Penicillin"],
        "medical_notes": "Advanced COPD. Requires supplemental oxygen. Palliative care team involved.",
        "last_visit_date": date(2026, 5, 20),
    },
    {
        "first_name": "Isabella", "last_name": "Torres",
        "date_of_birth": date(1995, 5, 11), "gender": "female",
        "blood_type": "O+", "email": "isabella.torres@email.com",
        "phone": "555-345-8877", "address": "219 Cypress St",
        "city": "Miami", "state": "FL", "zip_code": "33101",
        "status": "active", "primary_physician": "Dr. Rachel Goldstein",
        "insurance_provider": "Cigna", "insurance_id": "CGN-994021",
        "allergies": [],
        "medical_notes": "Routine gynecological care. Prenatal vitamins prescribed — planning for pregnancy.",
        "last_visit_date": date(2026, 3, 18),
    },
    {
        "first_name": "Walter", "last_name": "Kowalski",
        "date_of_birth": date(1958, 10, 27), "gender": "male",
        "blood_type": "B+", "email": "w.kowalski@email.com",
        "phone": "555-456-3311", "address": "11 Lakeview Dr",
        "city": "Detroit", "state": "MI", "zip_code": "48201",
        "status": "active", "primary_physician": "Dr. Sarah Chen",
        "insurance_provider": "BlueCross BlueShield", "insurance_id": "BCB-667734",
        "allergies": ["Peanuts"],
        "medical_notes": "Rheumatoid arthritis — on methotrexate. Joint swelling has decreased since dose adjustment.",
        "last_visit_date": date(2026, 4, 3),
    },
    {
        "first_name": "Yuki", "last_name": "Nakamura",
        "date_of_birth": date(2015, 7, 4), "gender": "female",
        "blood_type": "A+", "email": None,
        "phone": "555-567-9944", "address": "34 Bamboo Circle",
        "city": "Los Angeles", "state": "CA", "zip_code": "90001",
        "status": "active", "primary_physician": "Dr. Rachel Goldstein",
        "insurance_provider": "UnitedHealth", "insurance_id": "UHC-882031",
        "allergies": [],
        "medical_notes": "Pediatric patient. Routine wellness visit. Vaccines up to date.",
        "last_visit_date": date(2026, 5, 12),
    },
    {
        "first_name": "Bernard", "last_name": "Fontaine",
        "date_of_birth": date(1972, 3, 31), "gender": "male",
        "blood_type": "O-", "email": "b.fontaine@email.com",
        "phone": "555-678-1122", "address": "65 Bayou Rd",
        "city": "Baton Rouge", "state": "LA", "zip_code": "70801",
        "status": "discharged", "primary_physician": "Dr. James Okafor",
        "insurance_provider": "Humana", "insurance_id": "HUM-771203",
        "allergies": ["Latex", "Morphine"],
        "medical_notes": "Discharged after knee replacement surgery. Physical therapy prescribed 3x/week.",
        "last_visit_date": date(2026, 4, 30),
    },
    {
        "first_name": "Nadia", "last_name": "Petrova",
        "date_of_birth": date(1982, 9, 9), "gender": "female",
        "blood_type": "AB+", "email": "nadia.petrova@email.com",
        "phone": "555-789-4400", "address": "8 Birch Boulevard",
        "city": "Boston", "state": "MA", "zip_code": "02101",
        "status": "active", "primary_physician": "Dr. Linda Park",
        "insurance_provider": "Tufts Health", "insurance_id": "TH-330912",
        "allergies": ["Sulfa drugs"],
        "medical_notes": "Hypothyroidism and fibromyalgia. Multidisciplinary care plan in place.",
        "last_visit_date": date(2026, 2, 27),
    },
    {
        "first_name": "Samuel", "last_name": "Adeyemi",
        "date_of_birth": date(1990, 6, 16), "gender": "male",
        "blood_type": "O+", "email": "s.adeyemi@email.com",
        "phone": "555-891-6633", "address": "102 Cedar Ave",
        "city": "Philadelphia", "state": "PA", "zip_code": "19101",
        "status": "inactive", "primary_physician": "Dr. Rachel Goldstein",
        "insurance_provider": "Independence Blue Cross", "insurance_id": "IBC-885540",
        "allergies": [],
        "medical_notes": "Inactive patient. Last visit was routine physical — no issues flagged.",
        "last_visit_date": date(2025, 6, 8),
    },
    {
        "first_name": "Claire", "last_name": "Montague",
        "date_of_birth": date(1967, 11, 28), "gender": "female",
        "blood_type": "B-", "email": "claire.montague@email.com",
        "phone": "555-903-7755", "address": "47 Vineyard Way",
        "city": "Phoenix", "state": "AZ", "zip_code": "85001",
        "status": "active", "primary_physician": "Dr. Sarah Chen",
        "insurance_provider": "Cigna", "insurance_id": "CGN-119948",
        "allergies": ["Codeine"],
        "medical_notes": "Type 1 diabetes — insulin pump. Last HbA1c: 7.1%. Ophthalmology referral pending.",
        "last_visit_date": date(2026, 5, 6),
    },
    {
        "first_name": "Rashid", "last_name": "Khalil",
        "date_of_birth": date(2008, 1, 14), "gender": "male",
        "blood_type": "A-", "email": None,
        "phone": "555-012-8866", "address": "29 Tulip Drive",
        "city": "Minneapolis", "state": "MN", "zip_code": "55401",
        "status": "active", "primary_physician": "Dr. James Okafor",
        "insurance_provider": "BlueCross BlueShield", "insurance_id": "BCB-992021",
        "allergies": ["Tree nuts"],
        "medical_notes": "Pediatric patient. ADHD — methylphenidate 10mg. Academic performance improving.",
        "last_visit_date": date(2026, 3, 25),
    },
    {
        "first_name": "Dorothy", "last_name": "Simmons",
        "date_of_birth": date(1939, 4, 7), "gender": "female",
        "blood_type": "O+", "email": None,
        "phone": "555-113-2200", "address": "3 Sunflower Lane",
        "city": "Phoenix", "state": "AZ", "zip_code": "85002",
        "status": "critical", "primary_physician": "Dr. Linda Park",
        "insurance_provider": "Medicare", "insurance_id": "MCR-003-27-8891",
        "allergies": ["Penicillin", "Aspirin"],
        "medical_notes": "Advanced congestive heart failure. Daily monitoring required. Advanced directive on file.",
        "last_visit_date": date(2026, 5, 21),
    },
    {
        "first_name": "Liam", "last_name": "O'Brien",
        "date_of_birth": date(1980, 8, 3), "gender": "male",
        "blood_type": "B+", "email": "liam.obrien@email.com",
        "phone": "555-224-6611", "address": "18 Harbor View Rd",
        "city": "Portland", "state": "ME", "zip_code": "04101",
        "status": "active", "primary_physician": "Dr. Rachel Goldstein",
        "insurance_provider": "Anthem", "insurance_id": "ANT-558843",
        "allergies": ["Sulfa drugs", "Ibuprofen"],
        "medical_notes": "Chronic lower back pain managed with physical therapy. MRI scheduled for next quarter.",
        "last_visit_date": date(2026, 4, 17),
    },
]


async def seed_patients(db: AsyncSession) -> None:
    """Insert sample patients if the table is empty."""
    result = await db.execute(select(func.count()).select_from(Patient))
    count = result.scalar_one()
    if count > 0:
        return  # Already seeded

    for data in SAMPLE_PATIENTS:
        patient = Patient(id=uuid.uuid4(), **data)
        db.add(patient)

    await db.commit()
    print(f"✅ Seeded {len(SAMPLE_PATIENTS)} sample patients.")
